# Generated by Django 4.1.6 on 2023-02-12 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('steam_id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('game_title', models.CharField(max_length=50)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('list_name', models.CharField(max_length=50)),
                ('list_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id', models.ManyToManyField(to='rogueapp.game')),
                ('user_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rogueapp.userlist')),
            ],
        ),
    ]
