# Generated by Django 4.1.6 on 2023-02-12 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('steam_id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('game_title', models.CharField(max_length=64)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ListDetail',
            fields=[
                ('list_detail_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('list_name', models.CharField(max_length=50)),
                ('list_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListDetailContent',
            fields=[
                ('list_detail_content_id', models.AutoField(primary_key=True, serialize=False)),
                ('list_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rogueapp.listdetail')),
                ('steam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rogueapp.game')),
            ],
        ),
        migrations.AddField(
            model_name='listdetail',
            name='user_list',
            field=models.ForeignKey(db_column='UserList', on_delete=django.db.models.deletion.CASCADE, to='rogueapp.userlist'),
        ),
    ]
