# Generated by Django 4.1.6 on 2023-02-12 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rogueapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listdetail',
            name='user_list',
            field=models.ForeignKey(db_column='user_list_id', on_delete=django.db.models.deletion.CASCADE, to='rogueapp.userlist'),
        ),
    ]
