# Generated by Django 4.1.6 on 2023-02-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rogueapp', '0002_alter_listdetail_user_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='listdetailcontent',
            name='tier_rank',
            field=models.CharField(default=None, max_length=1, null=True),
        ),
    ]
