# Generated by Django 4.1.6 on 2023-02-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rogueapp', '0003_listdetailcontent_tier_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listdetailcontent',
            name='tier_rank',
            field=models.CharField(default='A', max_length=1, null=True),
        ),
    ]
