# Generated by Django 4.1.6 on 2023-02-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rogueapp', '0004_alter_listdetailcontent_tier_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='list_description',
            field=models.CharField(default='No description found.', max_length=500),
        ),
    ]
