# Generated by Django 4.1.6 on 2023-03-11 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rogueapp', '0007_favoritelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelist',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rogueapp.listdetail'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritelist',
            unique_together={('user', 'list')},
        ),
    ]
