# Generated by Django 4.1.6 on 2023-03-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rogueapp', '0008_alter_favoritelist_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.TextField(default=1716),
            preserve_default=False,
        ),
    ]
