# Generated by Django 4.1.6 on 2023-03-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rogueapp', '0009_genre_game_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listdetailcontent',
            name='tier_rank',
            field=models.CharField(default='Z', max_length=1, null=True),
        ),
    ]
